services:
  database:
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USERNAME:-app}
      MYSQL_PASSWORD: ${DB_PASSWORD:-app}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-app}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '--silent']
      interval: 10s
      timeout: 5s
      retries: 5
