services:
  database:
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD:-changeme}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      - database:/var/lib/mysql
    restart: always
volumes:
  database: {}
