# Bring a toolbox change to a project that already exists (ADR-0023).
# shellcheck shell=bash
#
# The files scaffold owns came from `common/` and `adapters/<name>/` at the
# commit .scaffold.toml records, so `git diff <that commit>..HEAD` over those
# paths, rewritten onto the project's layout, is exactly what it never received.

# One value for the whole run, set by cmd_update.
SCAFFOLD_UPDATE_FROM=""

# Rendered into mise.toml and rewritten further, so no patch against the
# template describes the result.
COMMON_PATCH_EXCLUDES=(':(exclude)common/mise.root.toml')

manifest_version() {
  local -r file="${1}/${SCAFFOLD_MANIFEST}"
  local version

  [[ -f "$file" ]] || return 1
  version="$(yq -p toml -oy -r '.version // ""' "$file" 2>/dev/null || true)"
  [[ -n "$version" ]] && [[ "$version" != "null" ]] || return 1
  printf '%s' "$version"
}

# One `<rel><tab><adapter>` line per application.
manifest_apps() {
  local -r project="$1"

  yq -p toml -oy -r '.apps // {} | to_entries | .[] | [.key, .value] | @tsv' \
    "${project}/${SCAFFOLD_MANIFEST}" 2>/dev/null || true
}

# Read back out of the project, not recomputed from `gh` or the directory name,
# which answer for this machine today.
project_image_owner() {
  local image
  image="$(project_image_base "$1")"
  image="${image#ghcr.io/}"
  printf '%s' "${image%%/*}"
}

project_image_name() {
  local image
  image="$(project_image_base "$1")"
  printf '%s' "${image##*/}"
}

# Anchored per header line: a path-shaped string in a context line is content,
# and rewriting it would corrupt its hunk. `#` delimits because the last rule
# alternates on `|`.
rewrite_patch_paths() {
  local -r from="$1" to="$2"
  sed -E \
    -e "s#^diff --git a/${from}#diff --git a/${to}#" \
    -e "s#^(diff --git a/[^ ]+) b/${from}#\1 b/${to}#" \
    -e "s#^--- a/${from}#--- a/${to}#" \
    -e "s#^\+\+\+ b/${from}#+++ b/${to}#" \
    -e "s#^(rename|copy) (from|to) ${from}#\1 \2 ${to}#"
}

# Context lines need the real values too, or no hunk matches anything.
substitute_placeholders() {
  local -r project="$1" rel="${2:-}"
  local owner name filter
  owner="$(project_image_owner "$project")"
  name="$(project_image_name "$project")"

  local -a rules=(
    -e "s|you/|${owner}/|g"
    -e "s|@PROJECT_NAME@|${name}|g"
    -e "s|@PROJECT_TITLE@|${name^}|g"
  )
  if [[ -n "$rel" ]]; then
    filter="$(app_service_key "$rel")"
    rules+=(-e "s|@APP_ROOT@|${rel}/|g" -e "s|@APP_FILTER@|${filter}|g")
  fi

  sed "${rules[@]}"
}

common_patch() {
  local -r project="$1"

  git -C "$SCAFFOLD_ROOT" diff "${SCAFFOLD_UPDATE_FROM}..HEAD" -- \
    common/ "${COMMON_PATCH_EXCLUDES[@]}" |
    rewrite_patch_paths 'common/' '' |
    substitute_placeholders "$project"
}

# The Dockerfile variant that survived generation is mapped onto `Dockerfile`,
# and the other dropped, since the project has no path for it.
adapter_patch() {
  local -r project="$1" rel="$2" adapter="$3"
  local -r dir="adapters/${adapter}"
  local kept dropped internal
  local -a excludes=()

  if [[ -f "${SCAFFOLD_ROOT}/${dir}/Dockerfile.workspace" ]] &&
    app_is_workspace_member "$project" "$rel"; then
    kept="Dockerfile.workspace"
    dropped="Dockerfile"
  else
    kept="Dockerfile"
    dropped="Dockerfile.workspace"
  fi

  for internal in "${ADAPTER_INTERNAL_FILES[@]}" "$dropped" "$kept"; do
    excludes+=(":(exclude)${dir}/${internal}")
  done

  {
    git -C "$SCAFFOLD_ROOT" diff "${SCAFFOLD_UPDATE_FROM}..HEAD" -- \
      "${dir}/" "${excludes[@]}"
    git -C "$SCAFFOLD_ROOT" diff "${SCAFFOLD_UPDATE_FROM}..HEAD" -- "${dir}/${kept}" |
      rewrite_patch_paths "${dir}/${kept}" "${dir}/Dockerfile"
  } |
    rewrite_patch_paths "${dir}/" "${rel}/" |
    substitute_placeholders "$project" "$rel"
}

update_patch() {
  local -r project="$1"
  local rel adapter

  common_patch "$project"
  while IFS=$'\t' read -r rel adapter; do
    [[ -n "$rel" ]] || continue
    [[ -d "${SCAFFOLD_ROOT}/adapters/${adapter}" ]] ||
      {
        warn "${rel} was generated by '${adapter}', which this toolbox no longer has — skipping it"
        continue
      }
    adapter_patch "$project" "$rel" "$adapter"
  done < <(manifest_apps "$project")
}

# The CI matrix and build targets are computed, so the patch brings their
# template form (`roots: '[]'`, `images: "[]"`), which builds nothing. Re-derived
# rather than excluded, which would drop every other change to those files; and
# only when empty, so correct targets are never rewritten.
resync_derived_files() {
  local -r project="$1"
  local rel

  sync_ci_roots "$project"

  local images
  images="$(yq -r '[.jobs[] | select(has("with")) | .with.images] | .[0] // ""' \
    "${project}/.github/workflows/build.yml" 2>/dev/null || true)"
  [[ "$images" == "[]" ]] || return 0

  while IFS=$'\t' read -r rel _; do
    [[ -n "$rel" ]] || continue
    register_image_target "$project" "$rel"
  done < <(manifest_apps "$project")
}
